name: 🚨🚨🚨
description: Report a Bug
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        Please do YOUR BEST to fill out the issue checklist bellow.
        Whenever in doubt, skip over the respective item.

  - type: checkboxes
    attributes:
      label: Please verify that you've followed these steps.
      options:
        - label: I opened a new shell.
          # required: true
        - label: "I ran: make bootstrap"
          # required: true
        - label: "I ran: make nuke all"
          # required: true
        - label: "I ran: make doctor"
          # required: true

  - type: textarea
    attributes:
      render: shell
      label: What does your system and relevant software look like?
      placeholder: Include all command output from `make doctor`.
    # validations:
    #   required: true

  - type: textarea
    attributes:
      label: What were you trying to do (and why)?
    # validations:
    #   required: true

  - type: textarea
    attributes:
      label: What happened?
      placeholder: Include all command output.
    # validations:
    #   required: true

  - type: textarea
    attributes:
      label: What did you expect to happen?
    # validations:
    #   required: true

  - type: textarea
    attributes:
      render: shell
      label: Step-by-step reproduction instructions.
    # validations:
    #   required: true

  - type: textarea
    attributes:
      label: What alternatives are there?
    # validations:
    #   required: true
