# blank_issues_enabled: false

contact_links:
  - name: Contact Y Software AB
    url: http://ysoftware.se
    about: Do you want a bug/feature to be prioritized? Do you want a support plan? The quickest way to get answers is contact us at https://ysoftware.se !
